const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  definitions: {
    Hotel: {
      $name: "Example Hotel",
      $location: "Example City",
      $rooms: [
        {
          capacity: 2,
          price: 100,
        },
      ],
    },
    User: {
      $id: 1,
      $username: "exampleuser",
      $firstName: "First",
      $lastName: "Last",
      $email: "user@example.com",
      $role: "User",
    },
    Room: {
      $id: 1,
      $capacity: 2,
      $price: 100,
      $hotelId: 1,
    },
    Reservation: {
      $id: 1,
      $userId: 1,
      $roomId: 1,
      $startDate: "2024-03-20",
      $endDate: "2024-03-25",
    },
    AuthMiddleware: {
      checkIfAuthorized: {
        description:
          "Ensures the user is logged in. Returns 401 Unauthorized if not logged in, 403 Forbidden if the user lacks permissions.",
      },
      checkIfAdmin: {
        description: "Ensures only Admins can access a route. Returns 403 Forbidden if unauthorized.",
      },
      canSeeUserDetails: {
        description: "Allows users to view their own details, or Admins to view all users.",
      },
      canSeeUserList: {
        description: "Allows only Admins to view the full user list.",
      },
    },
  },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = [
  "./routes/hotels.js",
  "./routes/users.js",
  "./routes/rooms.js",
  "./routes/auth.js",
  "./routes/reservations.js",
  "./routes/admin.js",
  "./routes/start.js",
];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./bin/www"); // Start server after generating Swagger file
});
